name: Docker Build - Incremental
# Pull the latest pre-built docker container
# Map current source into container
# Run make in the build directory - Note we don't build from scratch

# Because this runs on push actions, we get $GITHUB_SHA and it's set correctly (unlike on PR)

on:
  push:
    branches-ignore: # Pushes to master build docker containers (with make clean) through another action
      master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Get hash of latest PANDA container on Dockerhub # Somehow these quotes actually work
      run: echo "::set-env name=latesthash::$(curl  -s -S 'https://registry.hub.docker.com/v2/repositories/pandare/panda/tags/' | jq -cr '."results"[1]["name"]')"

    - name: Fetch docker container
      run: "docker pull pandare/panda:latest"

    - uses: actions/checkout@v1

      # Map new code into container (checkout action clones this commit to /home/runner/work/panda)
      # and run new new update.sh script
    - name: Map code into container and run update.sh to rebuild and test
      run: docker run --rm -v /home/runner/work/panda/panda/:/panda.new pandare/panda bash /panda.new/panda/docker/update.sh
