name: Docker Build - Incremental
# Pull the latest pre-built docker container
# Map current source into container
# Run make in the build directory - Note we don't build from scratch

on:
  push:
    branches-ignore: # Pushes to master build docker containers (with make clean) through another action
      master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Fetch docker container
      run: docker pull pandare/panda:latest

    - uses: actions/checkout@v1

      # Map new code into container (checkout action clones this commit to /home/runner/work/panda)
      # and run new new update.sh script
    - name: Map code into container and run update.sh to rebuild and test
      run: docker run --rm -v /home/runner/work/panda/panda/:/panda.new pandare/panda bash /panda.new/panda/docker/update.sh
