name: QEMU Checks

on:
  push:
    branches:
      - ci
  pull_request:
    branches:
      - master

jobs:
  build_and_check:
    runs-on: self-hosted
    strategy:
      matrix:
        target: [x86_64-softmmu, i386-softmmu, arm-softmmu, mips-softmmu] # NOTE: aarch64-softmmu currently unsupported

    steps:
    - name: Fetch pre-built bionic docker container
      run: docker pull pandare/panda:latest

    - uses: actions/checkout@v1

    - name: Clean build new code in container and run QEMU tests by arch
      run: >-
        docker run --name panda_test_${{ matrix.target }}_${GITHUB_RUN_ID}
        -v /home/runner/work/panda/panda/:/panda.new --rm -t
        -e PANDA_TEST=yes --cap-add SYS_NICE
        pandare/panda bash -c "rsync -rh /panda.new /panda && 
        (rm -rf /panda/build; mkdir /panda/build cd /panda/build) &&
        ../build.sh ${{ matrix.target }}"

    - name: Cleanup images # TODO can we run once at the end?
      run: docker system prune -af --volumes
